blank_issues_enabled: false
contact_links:
  - name: Security Disclosure
    url: https://github.com/<you>/mcpstack-tool/security/policy
    about: Please report security vulnerabilities responsibly.
