name: Pre-commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: "3.11"
      - run: uv venv
      - run: uv pip install -e .[dev]
      - run: uv run pre-commit run --all-files
